apiVersion: v1
kind: Service
metadata:
  name: welcome-app-service
  labels:
    app: welcome-app
spec:
  selector:
    app: welcome-app

  ports:
    - port: 3000
      targetPort: 3000

  type: LoadBalancer
